
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
// ...

// / ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7YMvWSaYY8PNqE0bNRdzinQY0TGxXvbE',
    appId: '1:871131262900:android:f7398fa510a119e01ecce1',
    messagingSenderId: '871131262900',
    projectId: 'doofie-7d819',
    storageBucket: 'doofie-7d819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXDOVUaRzMCG0Wa3vYrE20xmke5Wu1L0',
    appId: '1:871131262900:ios:3c1d17464b91c0711ecce1',
    messagingSenderId: '871131262900',
    projectId: 'doofie-7d819',
    storageBucket: 'doofie-7d819.firebasestorage.app',
    iosClientId: '871131262900-2t4d2460kclebgo0i72ntiq15okqtmm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.doofie',
  );
}
